### ISSUE TITLE
fix: this.queue.push is not a function

### ISSUE THREAD

**Issue by pahund** [KijijiCA/react-advertising#61]
In eBay's Track.js error tracking system for Kijiji Autos, we see reports like this:

```
this.queue.push is not a function. (In 'this.queue.push({id:t,customEventHandlers:r})', 'this.queue.push' is undefined)
```

These are errors happening in production, in our users' browsers.

Version 4.0.0.beta has improved the situation, so that the errors happen less frequently:

![less-frequent-with-4-beta](https://user-images.githubusercontent.com/1639313/118610183-c9f55d00-b7bb-11eb-97dc-61ae2a72ce93.png)

Stack trace:

![image](https://user-images.githubusercontent.com/1639313/118610417-0759ea80-b7bc-11eb-9c5c-a20b68dc344d.png)

The likely culprit is the de-initialization that happens when the `AdvertisingProvider` unmounts.

**Comment by filipecosta01** [comment]
@pahund I was going through the code and I spotted that the `queue` is being set to an object instead of an array in the unmount function of lifecycle. It could explain that during the unmount we still have some calls to activate and as the queue is now an object, we don't have the push function
.

https://github.com/eBayClassifiedsGroup/react-advertising/blob/3b62c84dc9c192dd7d8c5fc74df237dde2701941/src/Advertising.js#L94

I can open a PR to fix that, though I'm not sure how to replicate it consistently.
Do you have an alternative way to test?

**Comment by pahund** [comment]
@filipecosta01 

> @pahund I was going through the code and I spotted that the `queue` is being set to an object instead of an array in the unmount function of lifecycle. 
> I can open a PR to fix that, though I'm not sure how to replicate it consistently.

That's a great catch, please do open a PR!

> Do you have an alternative way to test?

Not yet. We could set up a Storybook story where we set up and tear down at the click of a button, then write a Cypress test. But for now, it will suffice if you change these blatantly wrong curly braces into square brackets.
